"""
Policy Verification Agent for TruthChain 2.0
Adapted from reference Contoso Claims Multi-Agent Insurance Platform.
Validates claim against domain policies (Motor Comprehensive, PMFBY Agriculture, Media License).
Supports semantic clause matching, limit verification, and exclusion detection.
"""

import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

# Sample Policy Database (Motor, PMFBY Agriculture, Media)
POLICY_DATABASE = {
    "motor": {
        "policy_type": "Motor Comprehensive & Collision Policy v4.2",
        "max_limit": 50000.0,
        "deductible": 500.0,
        "exclusions": ["DUI / Impaired driving", "Racing / Unlawful speed", "Pre-existing wear and tear"],
        "sections": {
            "sec_1_1": "Collision & Exterior Physical Damage: Covers collision with vehicle, stationary object, or rollover.",
            "sec_2_3": "Glass & Lamp Shatter: Glass repair covered subject to $100 dedicated glass deductible.",
            "sec_4_1": "Exclusions: Any intentional damage, staged collisions, or claims filed 30+ days after incident are excluded."
        }
    },
    "agriculture": {
        "policy_type": "PMFBY Pradhan Mantri Fasal Bima Yojana Policy v2.0",
        "max_limit": 100000.0,
        "deductible": 1000.0,
        "exclusions": ["Preventable pest infestation", "Post-harvest storage neglect", "Unregistered crop variety"],
        "sections": {
            "sec_3_1": "Inundation & Flood Loss: Covers localized inundation, unseasonal rainfall, and drought.",
            "sec_3_2": "Satellite NDVI Verification: Claims require satellite vegetation index deviation > 30%.",
            "sec_5_2": "Exclusions: Non-notified crop types or failure to inform within 72 hours of natural calamity."
        }
    },
    "media": {
        "policy_type": "Media Authenticity & Copyright Protection License v1.0",
        "max_limit": 75000.0,
        "deductible": 250.0,
        "exclusions": ["Uncredited commercial repurposing", "Synthetic deepfake generation"],
        "sections": {
            "sec_1_0": "Authenticity Guarantee: Protects against unauthorized alteration, deepfakes, and copyright infringement.",
            "sec_2_1": "Exclusions: Media intentionally generated by AI without provenance tags is excluded from coverage."
        }
    }
}


class PolicyCheckerAgent:
    """Evaluates claims against domain policy rules, coverage limits, and exclusions."""

    def __init__(self, model_version: str = "policy-v1.2"):
        self.model_version = model_version

    def verify_coverage(self, claim_data: Dict[str, Any], domain: str = "motor") -> Dict[str, Any]:
        """
        Determines coverage status (COVERED, PARTIALLY_COVERED, NOT_COVERED, INSUFFICIENT_EVIDENCE)
        and checks deductible limits and applicable exclusion clauses.
        """
        domain_key = domain.lower() if domain.lower() in POLICY_DATABASE else "motor"
        policy = POLICY_DATABASE[domain_key]

        claim_amount = float(claim_data.get("claim_amount", claim_data.get("estimated_cost", 0.0)))
        claim_text = str(claim_data.get("claim_text", "")).lower()

        coverage_status = "COVERED"
        cited_sections: List[str] = []
        exclusions_triggered: List[str] = []

        # Check max limit
        if claim_amount > policy["max_limit"]:
            coverage_status = "PARTIALLY_COVERED"
            cited_sections.append(f"[{policy['policy_type']} §Limit] Cap applies at ${policy['max_limit']:,.2f}")

        # Check exclusions
        for exclusion in policy["exclusions"]:
            if any(term in claim_text for term in exclusion.lower().split()):
                exclusions_triggered.append(exclusion)

        if exclusions_triggered:
            coverage_status = "NOT_COVERED" if len(exclusions_triggered) > 1 else "PARTIALLY_COVERED"
            cited_sections.append(f"[{policy['policy_type']} §Exclusions] Triggered exclusions: {', '.join(exclusions_triggered)}")

        # General section citations based on domain
        if domain_key == "motor":
            cited_sections.append(f"[{policy['policy_type']} §1.1] Exterior damage policy active.")
        elif domain_key == "agriculture":
            cited_sections.append(f"[{policy['policy_type']} §3.1] Flood/Inundation clause active.")
        else:
            cited_sections.append(f"[{policy['policy_type']} §1.0] Media provenance active.")

        approved_amount = min(max(0.0, claim_amount - policy["deductible"]), policy["max_limit"])

        return {
            "agent": "PolicyCheckerAgent",
            "domain": domain,
            "coverage_status": coverage_status,
            "policy_type": policy["policy_type"],
            "claimed_amount": claim_amount,
            "deductible": policy["deductible"],
            "policy_max_limit": policy["max_limit"],
            "approved_amount": approved_amount,
            "cited_sections": cited_sections,
            "exclusions_triggered": exclusions_triggered,
            "model_version": self.model_version,
        }
